version: '3.3'
services:
  db:
      container_name: 'local-blazor-db'
      image: 'mysql:5.7'
      volumes:
        - './MySQL:/var/lib/mysql'
      networks:
        - database
      ports:
        - 3306
      env_file:
        - dev.env
      restart: unless-stopped
  blazor:
    container_name: 'local-blazor'
    build:
      context: ./Blazor-Docker
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    networks:
      - default
      - database
    env_file:
      - dev.env
    volumes:
      - "./Blazor-Docker:/app"
    restart: unless-stopped

    
networks:
  database:
  default: