# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore
COPY . ./

EXPOSE 5000

ENTRYPOINT ["dotnet", "watch", "run", "--launch-profile", "Blazor-Docker-Development"]
